name: iOS CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.2"

            - name: Install Bundler & Fastlane
              run: |
                  gem install bundler
                  gem install fastlane

            - name: Build and Upload to TestFlight
              env:
                  APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
                  APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
                  APP_STORE_API_KEY_BASE64: ${{ secrets.APP_STORE_API_KEY_BASE64 }}
              run: fastlane Dev
