# name: iOS TestFlight

# on:
#     push:
#         branches: [main]
#     workflow_dispatch:

# jobs:
#     deploy:
#         name: Deploy to TestFlight
#         runs-on: macos-latest
#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v3
#               with:
#                   fetch-depth: 0

#             - name: Setup Ruby
#               uses: ruby/setup-ruby@v1
#               with:
#                   ruby-version: "3.1"
#                   bundler-cache: false

#             - name: Install dependencies
#               run: |
#                   bundle config path vendor/bundle
#                   bundle install --jobs 4 --retry 3

#             - name: Deploy to TestFlight
#               env:
#                   APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
#                   APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
#                   APP_STORE_API_KEY_BASE64: ${{ secrets.APP_STORE_API_KEY_BASE64 }}
#                   MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#               run: bundle exec fastlane beta
